import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import SimpleLoading from "./_components/SimpleLoading";

const flameBold = localFont({
  src: "../fonts/FlameBold.otf",
  variable: "--font-flame-bold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${flameBold.variable} antialiased`}>
        <SimpleLoading>
          <Header />
          {children}
          <Footer />
        </SimpleLoading>
      </body>
    </html>
  );
}
